# Dockerfile.frontend

FROM node:20-alpine

WORKDIR /app

COPY frontend/ /app/

RUN npm install
RUN npm run build

# Use nginx to serve the frontend
FROM nginx:stable-alpine as production
COPY --from=0 /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
